### PR TITLE
Update Tiles for OSRS Rev 209

### PR DESCRIPTION
**Pull request by Bonfire**
There are issues running the tile generator (as mentioned in #2), so some manual work was required when making these changes. Please let me know if you notice any issues. Thank you 🙂

### CODE REVIEW

**Comment by Bonfire** [comment]
Verified using my own fork (https://bonfire.github.io/osrs-map/) that the map appears to be behaving as expected

**Comment by Explv** [comment]
Thanks @Bonfire! When you say some manual work was required, what exactly do you mean? Were you unable to run the generator at all? From your issue, it looks like it failed to build one of the jars it depends on

**Comment by Bonfire** [comment]
> Thanks @Bonfire! When you say some manual work was required, what exactly do you mean? Were you unable to run the generator at all? From your issue, it looks like it failed to build one of the jars it depends on

The generator fails when attempting to find the `-jar-with-dependencies.jar` from RuneLite, as mentioned in #2. I was not able to figure out the exact cause, but my guess is an issue with building the jar or finding the jar (possibly path related?).

As a result, I had to make a few modifications to the generator in order to get it working correctly on my Windows machine. Modifications such as changing the various directory paths, utilizing the built libvips DLLs (for pyvips), and having to manually copy over the "full images" over.

As far as I can tell, everything should be exactly as it should be. Just required me to babysit the script and manually move some files/folders over, or update some lines to work on Windows.

**Comment by Bonfire** [comment]
I'm failing to see where the Docker image builds the RuneLite cache jars. Is the Dockerfile missing a step? Is the build step handled elsewhere?

**Comment by Explv** [comment]
> I'm failing to see where the Docker image builds the RuneLite cache jars. Is the Dockerfile missing a step? Is the build step handled elsewhere?

Hmm, you're right, that's weird, guess it needs updating to include that step.

I'll merge this PR for now. Thanks for your contribution! Much appreciated 👍

**Pull request merged**
